### ISSUE TITLE
Error in union(bad_words, words_add) : object 'bad_words' not found

### ISSUE THREAD

**Issue by jspncrb** [EmilHvitfeldt/offensiveR#1]
I get this error every time I try to use the add-in. 

I'm on Windows, latest offensiveR (EmilHvitfeldt/offensiveR@9b2b077), and I get the error regardless of whether I highlight some text, all text, use `offensive_check_string()`, or `offensive_check_files()`.

**Comment by EmilHvitfeldt** [comment]
Thanks for your feedback! Seems like it was a problem with declaring the proper namespace.

**Comment by jspncrb** [comment]
I think that the fix has broken the `words_add` and `words_ignore` arguments of `offensive_check_files` and `offensive_check_text`. 

I've only had a quick look and haven't got the time to test right now, but changing `word_checker()` to something like this might help and clarify?

```{r}
word_checker <- function (text, words_add = character(), words_ignore = character()) {
    bad_words_updated <- setdiff(union(offensiveR::bad_words, words_add), 
        words_ignore)
    text %>% purrr::map(~.x %>% tokenizers::tokenize_words() %>% 
        unlist() %>% intersect(bad_words_updated))
}
```
